export enum QueryKeys {
	STORY = "STORY",
	INTERACTIONS = "INTERACTIONS",
	USER = "USER",
	USER_PAYMENT = "USER_PAYMENT",
	USER_SECRET_KEY = "USER_SECRET_KEY",
	UPDATE = "UPDATE",

	GALLERY = "GALLERY",
	WIDE_VIDEOS = "WIDE_VIDEOS",
	VERTICAL_VIDEOS = "VERTICAL_VIDEOS",
	STORY_BOOKS = "STORY_BOOKS",
	TIK_TOK = "TIK_TOK",

	USER_PAGE_GALLERY = "USER_PAGE_GALLERY",
	USER_WIDE_VIDEOS = "USER_WIDE_VIDEOS",
	USER_VERTICAL_VIDEOS = "USER_VERTICAL_VIDEOS",
	USER_STORY_BOOKS = "USER_TORY_BOOKS",
	USER_TIK_TOK = "USER_TIK_TOK",

	LIBRARY_GALLERY = "LIBRARY_GALLERY",
	LIBRARY_WIDE_VIDEOS = "LIBRARY_WIDE_VIDEOS",
	LIBRARY_VERTICAL_VIDEOS = "LIBRARY_VERTICAL_VIDEOS",
	LIBRARY_STORY_BOOKS = "LIBRARY_STORY_BOOKS",
	LIBRARY_TIK_TOK = "LIBRARY_TIK_TOK",

	AMAZON_METADATA = "AMAZON_METADATA",
	AMAZON_CATEGORIES = "AMAZON_CATEGORIES",
	AMAZON_BOOK_METADATA = "AMAZON_BOOK_METADATA",

	USER_VIDEOS = "USER_VIDEOS",
	USER_PDFS = "USER_PDFS",
	USER_AMAZON_STATUS = "USER_AMAZON_STATUS",
	USER_AMAZON_ITEM = "USER_AMAZON_ITEM",
}
