export enum QueryKeys {
	STORY = "STORY",
	INTERACTIONS = "INTERACTIONS",
	USER = "USER",
	LIBRARY_STORIES = "LIBRARY_STORIES",
	WIDE_VIDEOS = "WIDE_VIDEOS",
	VERTICAL_VIDEOS = "VERTICAL_VIDEOS",
	CATEGORIES = "CATEGORIES",
	GALLERY = "GALLERY",
	STORY_BOOKS = "STORY_BOOKS",
	TIK_TOK = "TIK_TOK",
}
