export const genreOptions = [
	{ id: "all", value: "All Categories" },
	{ id: "adventure", value: "Adventure" },
	{ id: "fantasy", value: "Fantasy" },
	{ id: "science-fiction", value: "Science Fiction" },
	{ id: "children-stories", value: "Children Stories" },
	{ id: "drama", value: "Drama" },
	{ id: "mystery-and-thriller", value: "Mystery And Thriller" },
	{ id: "self-help-and-wellness", value: "Self Help And Wellness" },
	{ id: "technology-and-innovation", value: "Technology And Innovation" },
	{
		id: "business-and-entrepreneurship",
		value: "Business And Entrepreneurship",
	},
	{ id: "historical", value: "Historical" },
	{ id: "comedy", value: "Comedy" },
	{ id: "romance", value: "Romance" },
	{ id: "non-fiction", value: "Non Fiction" },
	{ id: "sports-and-recreation", value: "Sports And Recreation" },
	{ id: "horror", value: "Horror" },
	{ id: "travel-and-adventure", value: "Travel And Adventure" },
	{ id: "education", value: "Education" },
	{ id: "nature-and-environment", value: "Nature And Environment" },
	{ id: "music-and-audio", value: "Music And Audio" },
	{ id: "art-and-photography", value: "Art And Photography" },
	{ id: "creative-non-fiction", value: "Creative Non Fiction" },
	{ id: "parenting-and-family", value: "Parenting And Family" },
	{ id: "food-and-beverage", value: "Food And Beverage" },
	{ id: "home-and-garden", value: "Home And Garden" },
	{ id: "performance", value: "Performance" },
	{ id: "philosophy-and-religion", value: "Philosophy And Religion" },
	{ id: "automotive", value: "Automotive" },
	{ id: "culture-and-society", value: "Culture And Society" },
	{ id: "fan-fiction", value: "Fan Fiction" },
	{ id: "hobbies-and-crafts", value: "Hobbies And Crafts" },
	{ id: "other", value: "Other" },
];
